#!/usr/bin/env bash
#displays "bad luck" and "good luck" for 4th and 8th iterations respectively but displays "Best School" for the rest of the 10 iterations.
counter=1
while [ $counter -le 10 ];
do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
